### ISSUE TITLE
Tunability Grid in FlexiGrid defnition

### ISSUE THREAD

**Issue by ggalimba56** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext#45]
/* transmitter-tunability-grid */

    leaf central-frequency-step {
      type frequency-ghz;
      config false;
      description
        "This parameter indicates the transmitter tunability grid as
        the distance between two adjacent carrier frequencies of
        the transmitter tuning range.";
    } 

In flexi-grid does not make sense to talk about "grid" as the distance between two carriers may vary in the spectrum.
It make more sense to talk about central frequency granularity (or transceiver tuning granularity etc.)

Comment from Italo:
 
  I do not have a strong opinion but if my memory is not faulty, the name of this attribute
  has been discussed so better to check before changing it

Open the discussion to clarify.

**Comment by ggalimba56** [comment]
1 MHz gives us the granularity precision, not the steps.  e.g. with 3 decimal we can support 3.125GHz central frequency granularity.   I’m not sure the ROADM will ever have a MHz tunability

**Comment by sergiobelotti** [comment]
> /* transmitter-tunability-grid */
> 
> ```
> leaf central-frequency-step {
>   type frequency-ghz;
>   config false;
>   description
>     "This parameter indicates the transmitter tunability grid as
>     the distance between two adjacent carrier frequencies of
>     the transmitter tuning range.";
> } 
> ```
> 
> In flexi-grid does not make sense to talk about "grid" as the distance between two carriers may vary in the spectrum. It make more sense to talk about central frequency granularity (or transceiver tuning granularity etc.)
> 
> Comment from Italo:
> 
> I do not have a strong opinion but if my memory is not faulty, the name of this attribute has been discussed so better to check before changing it
> 
> Open the discussion to clarify.

In the draft section 2.5.4 we wrote "Supported transmitter tunability grid, the distance between two adjacent carrier frequencies (in GHz)" .  
We reference "carrier frequency" while if you refer Nominal central frequency granularity , you refer the spacing between allowed nominal central frequency e.g. 6.25 GHz . 
I think first we need to understand what we really indicate in this attribute .

**Comment by italobusi** [comment]
**2022-05-19 Daniel, Dieter, Gabriele, Jorge, Julien, Italo, Sergio**

Need to clarify in the description and in the optical impairments draft that this attribute deals with the granularity of the transmitter tunability of carrier central frequency

- [ ] @ggalimba56 : provide some text proposal

**Comment by ggalimba56** [comment]
what about this definition ?

leaf central-frequency-granularity {
  type frequency-ghz;
  config false;
  description
    "This parameter indicates the transmitter supported tunability granularity as
    the distance between two adjacent carrier frequencies of
    the transmitter tuning, that is the transmitter frequency 
    fine tuning steps e.g 3.125GHz or 0.001GHz. ";
}

**Comment by sergiobelotti** [comment]
> what about this definition ?
> 
> leaf central-frequency-granularity { type frequency-ghz; config false; description "This parameter indicates the transmitter supported tunability granularity as the distance between two adjacent carrier frequencies of the transmitter tuning, that is the transmitter frequency fine tuning steps e.g 3.125GHz or 0.001GHz. "; }

I'm a bit confused by the name of the attribute more than by the definition: in the flexible grid world , see RFC7698 clear definition, we have the "Nominal Central Frequency Granularity" , defined as "The spacing between allowed nominal central frequencies" , that is set to 6.25 GHz in G.694.1.
This "granularity" is used in the "allowed" frequencies calculation, with famous "n" value,  in the context of flexible grid , always as defined in G.694.1. 
Now , this attribute , instead , seems more related to the "tuning" of the device, i.e. transmitter , instead of frequencies in the spectrum?
Is correct my understanding and purpose of this attribute? 
If yes why do not name the attribute as "transmitter tuning" and in the definition avoiding to mention "...adjacent carrier frequencies and just saying: 
"This parameter indicates the transmitter frequency fine tuning steps e.g 3.125GHz or 0.001GHz. ";
Maybe we can modify the step number examples but the meaning in this case it seems very clear as well as the name of the attribute.
